#!/bin/bash

if [ -z "$1" ]; then
    lsblk 
    exit 1
else 
    sudo mount /dev/$1 /mnt/ipod/
fi

# Read the copying direction from the user
read -p "COPYING (F:FROM/T:TO) IPOD: " copying

# Determine the source or destination based on user input
if [[ "$copying" = "f" || "$copying" = "F" ]]; then
    sudo mv /mnt/ipod/Music/ /home/rayzen/Music/
elif [[ "$copying" = "t" || "$copying" = "T" ]]; then 
    sudo mv /home/rayzen/Music/ /mnt/ipod/Music/
else
    echo "Invalid copying direction selected."
    sudo umount /mnt/ipod/
    exit 1
fi



sudo umount /mnt/ipod/
