#!/bin/bash

if [ -z "$1" ]; then
    lsblk 
    exit 1
else 
    sudo mount /dev/$1 /mnt/ipod/
fi

# Read the copying direction from the user
read -p "COPYING (F:FROM/T:TO) IPOD: " copying

# Determine the source or destination based on user input
if [[ "$copying" = "f" || "$copying" = "F" ]]; then
    statement="/mnt/ipod/"
elif [[ "$copying" = "t" || "$copying" = "T" ]]; then 
    statement="/home/rayzen/Music/"
else
    echo "Invalid copying direction selected."
    sudo umount /mnt/ipod/
    exit 1
fi

echo "$statement"

read -p "Which file to copy (M: Music Playlists, P: Podcast, A: All): " files

if [[ "$files" = "M" || "$files" = "m" ]]; then
    cp -r "${statement}Music Playlists/" /home/rayzen/Music/
elif [[ "$files" = "P" || "$files" = "p" ]]; then
    cp -r "${statement}podcast" /home/rayzen/Music/
elif [[ "$files" = "A" || "$files" = "a" ]]; then
    cp -r "${statement}*" /home/rayzen/Music/
else
    echo "Invalid option selected."
    sudo umount /mnt/ipod/
    exit 1
fi

sudo umount /mnt/ipod/
